'use client'

import { useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, BatteryCharging, Bell, CalendarDays, ChevronDown, CircleHelp, ClipboardList, CreditCard, Gauge, LayoutDashboard, Menu, Moon, Search, Settings, ShieldCheck, Sun, Users, Wrench, X, Zap } from 'lucide-react'
import { Button } from '@/components/ui/button'

const revenueData = [{ name: 'Mansarovar', value: 46500 }, { name: 'Vaishali Nagar', value: 38200 }, { name: 'Malviya Nagar', value: 32100 }, { name: 'C-Scheme', value: 27400 }, { name: 'Tonk Road', value: 21800 }]
const energyData = [{ name: 'Aarav', value: 184 }, { name: 'Priya', value: 156 }, { name: 'Rohan', value: 131 }, { name: 'Ananya', value: 118 }, { name: 'Vikram', value: 94 }]
const sessions = [{ id: 'SES-24081', customer: 'Aarav Sharma', station: 'Mansarovar Hub', duration: '48 min', energy: '32.4 kWh', cost: '₹ 486' }, { id: 'SES-24080', customer: 'Priya Mehta', station: 'C-Scheme Central', duration: '35 min', energy: '24.1 kWh', cost: '₹ 362' }, { id: 'SES-24079', customer: 'Rohan Gupta', station: 'Vaishali Nagar', duration: '1h 12 min', energy: '48.7 kWh', cost: '₹ 731' }, { id: 'SES-24078', customer: 'Ananya Singh', station: 'Malviya Nagar', duration: '26 min', energy: '17.8 kWh', cost: '₹ 267' }]
const nav = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Stations', icon: Gauge }, { label: 'Chargers', icon: BatteryCharging }, { label: 'Bookings', icon: CalendarDays }, { label: 'Sessions', icon: Activity }, { label: 'Payments', icon: CreditCard }, { label: 'Customers', icon: Users }, { label: 'Maintenance', icon: Wrench }]

function StatCard({ label, value, trend, icon: Icon, tone }: { label: string; value: string; trend: string; icon: typeof Gauge; tone: string }) {
  return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={20} /></div><div><p className="muted small">{label}</p><p className="stat-value">{value}</p><p className="trend">{trend}</p></div></div>
}

export default function Page() {
  const [active, setActive] = useState('Overview')
  const [dark, setDark] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  const [query, setQuery] = useState('')
  const filteredSessions = useMemo(() => sessions.filter((s) => `${s.customer} ${s.station} ${s.id}`.toLowerCase().includes(query.toLowerCase())), [query])

  return <div className={dark ? 'app dark' : 'app'}>
    <aside className={mobileOpen ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark"><Zap size={19} fill="currentColor" /></div><div><strong>Charge<span>Flow</span></strong><small>JAIPUR OPERATIONS</small></div><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={18} /></button></div>
      <nav><p className="nav-heading">MAIN MENU</p>{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false) }} className={active === label ? 'nav-item active' : 'nav-item'}><Icon size={18} /><span>{label}</span>{label === 'Bookings' && <em>6</em>}</button>)}</nav>
      <div className="sidebar-bottom"><button className="nav-item"><Settings size={18} /><span>Settings</span></button><button className="nav-item"><CircleHelp size={18} /><span>Help center</span></button><div className="user-chip"><div className="avatar">RS</div><div><strong>Rajiv Sharma</strong><small>Operations manager</small></div><ChevronDown size={15} /></div></div>
    </aside>
    <main className="main"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{active}</strong></div><div className="top-actions"><div className="search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search anything..." /><kbd>⌘ K</kbd></div><button className="icon-button" aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-button notification" aria-label="Notifications"><Bell size={18} /><i /></button></div></header>
      <div className="content"><div className="page-intro"><div><p className="eyebrow">TUESDAY, 08 OCT 2024 <span className="live-dot" /> SYSTEMS OPERATIONAL</p><h1>Good morning, Rajiv.</h1><p className="muted">Here&apos;s what&apos;s happening across your charging network.</p></div><Button className="export-button"><ClipboardList size={16} /> Export report</Button></div>
        <section className="stats-grid"><StatCard label="Total revenue" value="₹ 2,84,650" trend="↑ 12.8% vs last month" icon={CreditCard} tone="green" /><StatCard label="Energy delivered" value="18,426 kWh" trend="↑ 8.4% vs last month" icon={Zap} tone="blue" /><StatCard label="Active stations" value="12 / 14" trend="2 stations in maintenance" icon={Gauge} tone="orange" /><StatCard label="Available chargers" value="38 / 56" trend="68% availability rate" icon={BatteryCharging} tone="purple" /><StatCard label="Active bookings" value="24" trend="↑ 6 from yesterday" icon={CalendarDays} tone="rose" /></section>
        <section className="chart-grid"><div className="panel chart-panel"><div className="panel-header"><div><h2>Revenue by station</h2><p className="muted small">Monthly revenue performance</p></div><select aria-label="Revenue period"><option>Last 30 days</option><option>Last 90 days</option></select></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={revenueData} margin={{ top: 12, right: 10, left: -18, bottom: 0 }}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="var(--border)" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} tickFormatter={(v) => `₹${v / 1000}k`} /><Tooltip cursor={{ fill: 'var(--surface-2)' }} formatter={(v) => [`₹${Number(v).toLocaleString('en-IN')}`, 'Revenue']} /><Bar dataKey="value" fill="var(--green)" radius={[5, 5, 0, 0]} barSize={33} /></BarChart></ResponsiveContainer></div></div><div className="panel chart-panel"><div className="panel-header"><div><h2>Customer energy usage</h2><p className="muted small">Top customers this month</p></div><button className="dots">•••</button></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={energyData} layout="vertical" margin={{ top: 0, right: 20, left: 0, bottom: 0 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" stroke="var(--border)" /><XAxis type="number" hide /><YAxis type="category" dataKey="name" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} width={45} /><Tooltip cursor={{ fill: 'var(--surface-2)' }} formatter={(v) => [`${v} kWh`, 'Energy']} /><Bar dataKey="value" fill="var(--blue)" radius={[0, 5, 5, 0]} barSize={20} /></BarChart></ResponsiveContainer></div></div></section>
        <section className="panel table-panel"><div className="panel-header"><div><h2>Recent charging sessions</h2><p className="muted small">Latest activity across all stations</p></div><button className="link-button">View all sessions <span>→</span></button></div><div className="table-wrap"><table><thead><tr><th>SESSION ID</th><th>CUSTOMER</th><th>STATION</th><th>DURATION</th><th>ENERGY</th><th>COST</th><th /></tr></thead><tbody>{filteredSessions.map((session) => <tr key={session.id}><td><span className="session-id">{session.id}</span></td><td><div className="person"><div className="mini-avatar">{session.customer.split(' ').map((x) => x[0]).join('')}</div>{session.customer}</div></td><td>{session.station}</td><td>{session.duration}</td><td>{session.energy}</td><td><strong>{session.cost}</strong></td><td><button className="row-more">•••</button></td></tr>)}</tbody></table>{filteredSessions.length === 0 && <div className="empty">No sessions match your search.</div>}</div></section>
        <footer><span>ChargeFlow Admin · v2.4.0</span><span><ShieldCheck size={13} /> All systems operational</span></footer>
      </div></main>
    </div>
}
